---
- name: Deploy to Tomcat
  hosts: web
  become: yes

  tasks:

    - name: Stop Tomcat
      shell: /opt/tomcat/bin/shutdown.sh

    - name: Copy WAR file to Tomcat
      copy:
        src: "{{ lookup('env','WORKSPACE') }}/target/mavenweb.war"
        dest: "/opt/tomcat/webapps/mavenweb.war"

    - name: Start Tomcat
      shell: /opt/tomcat/bin/startup.sh
